name: flutter_auth0
description: Flutter toolkit for Auth0 API and web pkce flow authentication
author: Denny Segura <dev.dennysegura@gmail.com>
homepage: https://github.com/devdennysegura/flutter-auth0
version: 0.6.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.5

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.flutterauth0
        pluginClass: FlutterAuth0Plugin